# Generated by Django 4.0.5 on 2022-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_rename_descrição_curso_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('descricao', models.TextField()),
                ('duracao', models.DurationField()),
                ('video_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='autor',
            field=models.CharField(blank=True, default='EU', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
