# Generated by Django 4.0.5 on 2022-07-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_aula_curso_slug_alter_curso_autor_alter_curso_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='nome',
            field=models.CharField(max_length=128),
        ),
    ]
